export const gears = [
  {
    id: 'cloth',
    name: 'Cloth',
    imageUrl: 'https://imgur.com/9jQc0IC.png',
    location: 'Starting',
  },
  {
    id: 'foundingStone',
    name: 'Founding Stone',
    imageUrl: 'https://imgur.com/2zsXe2N.png',
    location: 'Starting',
  },
  {
    id: 'counterWeightedAxe',
    name: 'Counterweighted Axe',
    imageUrl: 'https://imgur.com/39cSWbq.png',
    location: 'Weapon Crafter',
    top: 'red',
  },
  {
    id: 'fingerOfgod',
    name: 'finger of God',
    imageUrl: 'https://imgur.com/vZAwyfV.png',
    location: 'Weapon Crafter',
  },
  {
    id: 'rainbowKatana',
    name: 'Rainbow Katana',
    imageUrl: 'https://imgur.com/AVJmCSN.png',
    location: 'Weapon Crafter',
    left: 'red',
  },
  {
    id: 'scrapDagger',
    name: 'Scrap Dagger',
    imageUrl: 'https://imgur.com/f0kyO50.png',
    location: 'Weapon Crafter',
    right: 'red',
    bottom: 'red',
  },
  {
    id: 'scrapSword',
    name: 'Scrap Sword',
    imageUrl: 'https://imgur.com/Fs1jftj.png',
    location: 'Weapon Crafter',
    top: 'blue',
  },
  {
    id: 'skullcapHammer',
    name: 'Skullcap Hammer',
    imageUrl: 'https://imgur.com/071d6fE.png',
    location: 'Weapon Crafter',
    bottom: 'green',
  },
  {
    id: 'whistlingMace',
    name: 'Whistling Mace',
    imageUrl: 'https://imgur.com/t2QUvMY.png',
    location: 'Weapon Crafter',
    bottom: 'green',
  },
  {
    id: 'zanbato',
    name: 'Zanbato',
    imageUrl: 'https://imgur.com/rxvY6Hc.png',
    location: 'Weapon Crafter',
    top: 'red',
    right: 'green',
  },
  {
    id: 'bloodSheath',
    name: 'Blood Shealth',
    imageUrl: 'https://imgur.com/XwyOxOa.png',
    location: 'Weapon Crafter',
    left: 'black',
  },
  {
    id: 'beastKnuckle',
    name: 'Beast Knuckle',
    imageUrl: 'https://imgur.com/09dRCMs.png',
    location: 'Stone Circle',
  },
  {
    id: 'bloodPaint',
    name: 'Blood Paint',
    imageUrl: 'https://imgur.com/aelkCmq.png',
    location: 'Stone Circle',
    left: 'black',
    right: 'black',
  },
  {
    id: 'blueCharm',
    name: 'Blue Charm',
    imageUrl: 'https://imgur.com/xJRP5YP.png',
    location: 'Stone Circle',
  },
  {
    id: 'boneEarrings',
    name: 'Bone Earrings',
    imageUrl: 'https://imgur.com/mpetEBT.png',
    location: 'Stone Circle',
  },
  {
    id: 'bossMehndi',
    name: 'Boss Mehndi',
    imageUrl: 'https://imgur.com/6UKyazf.png',
    location: 'Stone Circle',
  },
  {
    id: 'greenCharm',
    name: 'Green Charm',
    imageUrl: 'https://imgur.com/1Tz05E6.png',
    location: 'Stone Circle',
  },
  {
    id: 'lanceOfLonginus',
    name: 'Lance of Longinus',
    imageUrl: 'https://imgur.com/Zsjf1Yv.png',
    location: 'Stone Circle',
  },
  {
    id: 'redCharm',
    name: 'Red Charm',
    imageUrl: 'https://imgur.com/eC9WC7L.png',
    location: 'Stone Circle',
  },
  {
    id: 'screamingBracers',
    name: 'Screaming Bracer',
    imageUrl: 'https://imgur.com/jqONk2S.png',
    location: 'Stone Circle',
    top: 'green',
    left: 'red',
  },
  {
    id: 'screamingCoat',
    name: 'Screaming Coat',
    imageUrl: 'https://imgur.com/jkpRPMb.png',
    location: 'Stone Circle',
    top: 'blue',
    left: 'green',
    right: 'blue',
    bottom: 'green',
  },
  {
    id: 'screamingHorns',
    name: 'Screaming Horns',
    imageUrl: 'https://imgur.com/PAeYNlQ.png',
    location: 'Stone Circle',
    bottom: 'green',
  },
  {
    id: 'screamingLegWarmers',
    name: 'Screaming Leg Warmers',
    imageUrl: 'https://imgur.com/7vQBWX8.png',
    location: 'Stone Circle',
    top: 'blue',
    right: 'red',
  },
  {
    id: 'screamingSkirt',
    name: 'Screaming Skirt',
    imageUrl: 'https://imgur.com/SBIzDB9.png',
    location: 'Stone Circle',
    bottom: 'blue',
    right: 'green',
  },
  {
    id: 'bandages',
    name: 'Bandages',
    imageUrl: 'https://imgur.com/UndwGMz.png',
    location: 'Skinnery',
    left: 'blue',
    bottom: 'green',
  },
  {
    id: 'rawhideBoots',
    name: 'Rawhide Boots',
    imageUrl: 'https://imgur.com/wnq1TwU.png',
    location: 'Skinnery',
  },
  {
    id: 'rawhideDrum',
    name: 'Rawhide Drum',
    imageUrl: 'https://imgur.com/gYKSqXF.png',
    location: 'Skinnery',
    left: 'green',
  },
  {
    id: 'rawhideGloves',
    name: 'Rawhide Gloves',
    imageUrl: 'https://imgur.com/rHGLjEv.png',
    location: 'Skinnery',
    left: 'red',
  },
  {
    id: 'rawhideHeadband',
    name: 'Rawhide Headband',
    imageUrl: 'https://imgur.com/gPO2txw.png',
    location: 'Skinnery',
    bottom: 'blue',
  },
  {
    id: 'rawhidePants',
    name: 'Rawhide Pants',
    imageUrl: 'https://imgur.com/IHCUhME.png',
    location: 'Skinnery',
  },
  {
    id: 'rawhideVest',
    name: 'Rawhide Vest',
    imageUrl: 'https://imgur.com/H6IMoy0.png',
    location: 'Skinnery',
    top: 'blue',
    right: 'red',
  },
  {
    id: 'rawhideWhip',
    name: 'Rawhide Whip',
    imageUrl: 'https://imgur.com/z3XlTvH.png',
    location: 'Skinnery',
  },
  {
    id: 'driedAcanthus',
    name: 'Dried Acanthus',
    imageUrl: 'https://imgur.com/OOjmlWH.png',
    location: 'Organ Grinder',
  },
  {
    id: 'fecalSalve',
    name: 'Fecal Salve',
    imageUrl: 'https://imgur.com/TokbrrA.png',
    location: 'Organ Grinder',
    left: 'blue',
  },
  {
    id: 'luckyCharm',
    name: 'Luck Charm',
    imageUrl: 'https://imgur.com/r8nEPsZ.png',
    location: 'Organ Grinder',
    left: 'blue',
    right: 'blue',
  },
  {
    id: 'monsterGrease',
    name: 'Monster Grease',
    imageUrl: 'https://imgur.com/6E1PcCb.png',
    location: 'Organ Grinder',
    left: 'green',
  },
  {
    id: 'monsterToothNecklace',
    name: 'Monster Tooth Necklace',
    imageUrl: 'https://imgur.com/UnxARn0.png',
    location: 'Organ Grinder',
    right: 'red',
  },
  {
    id: 'birdBread',
    name: 'Bird Bread',
    imageUrl: 'https://imgur.com/ta0pEBS.png',
    location: 'Plumery',
    right: 'green',
  },
  {
    id: 'bloomSphere',
    name: 'Bloom Sphere',
    imageUrl: 'https://imgur.com/35LsJO2.png',
    location: 'Plumery',
    left: 'green',
    right: 'blue',
  },
  {
    id: 'crestCrown',
    name: 'Crest Crown',
    imageUrl: 'https://imgur.com/rAvbvci.png',
    location: 'Plumery',
    left: 'red',
    right: 'green',
    top: 'blue',
    bottom: 'blue',
  },
  {
    id: 'featherMantle',
    name: 'Feather Mantle',
    imageUrl: 'https://imgur.com/82dRgxP.png',
    location: 'Plumery',
    left: 'blue',
    right: 'green',
    bottom: 'red',
  },
  {
    id: 'hollowpointArrow',
    name: 'Hollowpoint Arrow',
    imageUrl: 'https://imgur.com/XQ0E5Pf.png',
    location: 'Plumery',
  },
  {
    id: 'featherShield',
    name: 'Feather Shield',
    imageUrl: 'https://imgur.com/4GIp3WT.png',
    location: 'Plumery',
  },
  {
    id: 'hollowSword',
    name: 'Hollow Sword',
    imageUrl: 'https://imgur.com/qTiMXCl.png',
    location: 'Plumery',
  },
  {
    id: 'hoursRing',
    name: 'Hours Ring',
    imageUrl: 'https://imgur.com/5e8lQHG.png',
    location: 'Plumery',
  },
  {
    id: 'phoenixFaulds',
    name: 'Phoenix Faulds',
    imageUrl: 'https://imgur.com/pyIizbt.png',
    location: 'Plumery',
  },
  {
    id: 'phoenixGauntlet',
    name: 'Phoenix Gauntlet',
    imageUrl: 'https://imgur.com/pi8IjgH.png',
    location: 'Plumery',
  },
  {
    id: 'phoenixGreaves',
    name: 'Phoenix Greaves',
    imageUrl: 'https://imgur.com/SpUIxHD.png',
    location: 'Plumery',
    right: 'red',
  },
  {
    id: 'arcBow',
    name: 'Arc Bow',
    imageUrl: 'https://imgur.com/Zww7KQK.png',
    location: 'Plumery',
    left: 'red',
    right: 'green',
  },
  {
    id: 'phoenixHelm',
    name: 'Phoenix Helm',
    imageUrl: 'https://imgur.com/4wkdYy4.png',
    location: 'Plumery',
    bottom: 'blue',
  },
  {
    id: 'phoenixPlackart',
    name: 'Phoenix Plackart',
    imageUrl: 'https://imgur.com/pvV31Ct.png',
    location: 'Plumery',
    top: 'blue',
    left: 'green',
    right: 'red',
  },
  {
    id: 'sonicTomahawk',
    name: 'Sonic Tomahawk',
    imageUrl: 'https://imgur.com/rnCRVT7.png',
    location: 'Plumery',
    left: 'red',
  },
  {
    id: 'hunterWhip',
    name: 'Hunter Whip',
    imageUrl: 'https://imgur.com/yKJAAod.png',
    location: 'Leather Worker',
    top: 'blue',
    right: 'blue',
  },
  {
    id: 'leatherBoots',
    name: 'Leather Boots',
    imageUrl: 'https://imgur.com/j1DygQO.png',
    location: 'Leather Worker',
    left: 'green',
    right: 'green',
  },
  {
    id: 'leatherBracers',
    name: 'Leather Bracers',
    imageUrl: 'https://imgur.com/pRHwx9O.png',
    location: 'Leather Worker',
    right: 'green',
  },
  {
    id: 'leatherCuirass',
    name: 'Leather Cuirass',
    imageUrl: 'https://imgur.com/gEzpWzA.png',
    location: 'Leather Worker',
    top: 'red',
    bottom: 'blue',
  },
  {
    id: 'leatherMask',
    name: 'Leather Mask',
    imageUrl: 'https://imgur.com/tJ5b60I.png',
    location: 'Leather Worker',
    top: 'blue',
    bottom: 'red',
  },
  {
    id: 'leatherSkirt',
    name: 'Leather Skirt',
    imageUrl: 'https://imgur.com/ulyDOui.png',
    location: 'Leather Worker',
    bottom: 'green',
  },
  {
    id: 'roundLeatherShield',
    name: 'Round Leather Shield',
    imageUrl: 'https://imgur.com/77wcDen.png',
    location: 'Leather Worker',
    top: 'green',
  },
  {
    id: 'deathMask',
    name: 'Death Mask',
    imageUrl: 'https://imgur.com/1Mb0EBH.png',
    location: 'Mask Maker',
  },
  {
    id: 'godMask',
    name: 'God Mask',
    imageUrl: 'https://imgur.com/Xp5ULMd.png',
    location: 'Mask Maker',
  },
  {
    id: 'manMask',
    name: 'Man Mask',
    imageUrl: 'https://imgur.com/xXrlXqi.png',
    location: 'Mask Maker',
  },
  {
    id: 'phoenixMask',
    name: 'Phoenix Mask',
    imageUrl: 'https://imgur.com/P5Y9MjR.png',
    location: 'Mask Maker',
  },
  {
    id: 'antelopeMask',
    name: 'Antelope Mask',
    imageUrl: 'https://imgur.com/x298A1F.png',
    location: 'Mask Maker',
  },
  {
    id: 'boneSickle',
    name: 'Bone Sickle',
    imageUrl: 'https://imgur.com/X3iyGQ6.png',
    location: 'Bone Smith',
    top: 'green',
  },
  {
    id: 'skullHelm',
    name: 'Skull Helm',
    imageUrl: 'https://imgur.com/nM3aCUp.png',
    location: 'Bone Smith',
    bottom: 'red',
  },
  {
    id: 'boneAxe',
    name: 'Bone Axe',
    imageUrl: 'https://imgur.com/hxGp8O5.png',
    location: 'Bone Smith',
    left: 'red',
  },
  {
    id: 'boneBlade',
    name: 'Bone Blade',
    imageUrl: 'https://imgur.com/ZMCGimQ.png',
    location: 'Bone Smith',
    left: 'red',
  },
  {
    id: 'boneDagger',
    name: 'Bone Dagger',
    imageUrl: 'https://imgur.com/VbryH2W.png',
    location: 'Bone Smith',
    left: 'red',
    top: 'red',
  },
  {
    id: 'boneDart',
    name: 'Bone Dart',
    imageUrl: 'https://imgur.com/bQxu4aS.png',
    location: 'Bone Smith',
    left: 'red',
  },
  {
    id: 'bonePickaxe',
    name: 'Bone Pickaxe',
    imageUrl: 'https://imgur.com/zOVXeyA.png',
    location: 'Bone Smith',
    top: 'green',
  },
  {
    id: 'catFangKnife',
    name: 'Cat Fang Knife',
    imageUrl: 'https://imgur.com/zvSQGxy.png',
    location: 'Catarium',
    top: 'red',
    left: 'red',
    right: 'red',
    bottom: 'red',
  },
  {
    id: 'catGutBow',
    name: 'Cat Gut Bow',
    imageUrl: 'https://imgur.com/M1btKnw.png',
    location: 'Catarium',
    top: 'blue',
  },
  {
    id: 'clawHeadArrow',
    name: 'Claw Head Arrow',
    imageUrl: 'https://imgur.com/mqEsIr0.png',
    location: 'Catarium',
  },
  {
    id: 'frenzyDrink',
    name: 'Frenzy Drink',
    imageUrl: 'https://imgur.com/382IiKy.png',
    location: 'Catarium',
  },
  {
    id: 'kingSpear',
    name: 'King Spear',
    imageUrl: 'https://imgur.com/tQOGMWM.png',
    location: 'Catarium',
    right: 'red',
  },
  {
    id: 'lionBeastKatar',
    name: 'Lion Beast Katar',
    imageUrl: 'https://imgur.com/EQmL8PU.png',
    location: 'Catarium',
  },
  {
    id: 'lionHeaddress',
    name: 'Lion Headdress',
    imageUrl: 'https://imgur.com/47j5ROx.png',
    location: 'Catarium',
  },
  {
    id: 'lionSkinCloak',
    name: 'Lion Skin Cloak',
    imageUrl: 'https://imgur.com/eatUtnI.png',
    location: 'Catarium',
    right: 'green',
  },
  {
    id: 'whiskerHarp',
    name: 'Whisker Harp',
    imageUrl: 'https://imgur.com/9vp5J9H.png',
    location: 'Catarium',
    left: 'blue',
  },
  {
    id: 'whiteLionBoots',
    name: 'White Lion Boots',
    imageUrl: 'https://imgur.com/dw4opZc.png',
    location: 'Catarium',
    right: 'red',
    bottom: 'red',
  },
  {
    id: 'whiteLionCoat',
    name: 'White Lion Coat',
    imageUrl: 'https://imgur.com/G4n82wU.png',
    location: 'Catarium',
    top: 'blue',
  },
  {
    id: 'whiteLionGauntlet',
    name: 'White Lion Gauntlet',
    imageUrl: 'https://imgur.com/1EmG2bA.png',
    location: 'Catarium',
  },
  {
    id: 'whiteLionHelm',
    name: 'White Lion Helm',
    imageUrl: 'https://imgur.com/oEt3Btb.png',
    location: 'Catarium',
    bottom: 'red',
  },
  {
    id: 'whiteLionSkirt',
    name: 'White Lion Skirt',
    imageUrl: 'https://imgur.com/0fvrLTm.png',
    location: 'Catarium',
    left: 'red',
    right: 'red',
  },
  {
    id: 'catEyeCirclet',
    name: 'Cat Eye Circlet',
    imageUrl: 'https://imgur.com/xdkphRD.png',
    location: 'Catarium',
    left: 'blue',
  },
  {
    id: 'bugTrap',
    name: 'Bug Trap',
    imageUrl: 'https://imgur.com/U4GQDgW.png',
    location: 'Barber Surgeon',
  },
  {
    id: 'firstAidKit',
    name: 'First Aid Kit',
    imageUrl: 'https://imgur.com/4Jrd7Nb.png',
    location: 'Barber Surgeon',
    left: 'green',
    right: 'green',
    top: 'green',
    bottom: 'green',
  },
  {
    id: 'elderEarrings',
    name: 'Elder Earrings',
    imageUrl: 'https://imgur.com/wjP18Kf.png',
    location: 'Barber Surgeon',
    left: 'red',
    right: 'green',
    bottom: 'blue',
  },
  {
    id: 'speedPowder',
    name: 'Speed Powder',
    imageUrl: 'https://imgur.com/U1ZI21Z.png',
    location: 'Barber Surgeon',
    right: 'blue',
  },
  {
    id: 'scavengerKit',
    name: 'Scavenger Kit',
    imageUrl: 'https://imgur.com/SjxofgF.png',
    location: 'Barber Surgeon',
    bottom: 'green',
  },
  {
    id: 'muskBomb',
    name: 'Musk Bomb',
    imageUrl: 'https://imgur.com/2CTC4KR.png',
    location: 'Barber Surgeon',
  },
  {
    id: 'brainMint',
    name: 'Brain Mint',
    imageUrl: 'https://imgur.com/RhsZHSt.png',
    location: 'Barber Surgeon',
    top: 'green',
    left: 'blue',
  },
  {
    id: 'almanac',
    name: 'Almanac',
    imageUrl: 'https://imgur.com/hjrXXvX.png',
    location: 'Barber Surgeon',
    right: 'blue',
  },
  {
    id: 'perfectSlayer',
    name: 'Perfect Slayer',
    imageUrl: 'https://imgur.com/sL748DF.png',
    location: 'Blacksmith',
    bottom: 'red',
  },
  {
    id: 'ringWhip',
    name: 'Ring Whip',
    imageUrl: 'https://imgur.com/kBBPZRS.png',
    location: 'Blacksmith',
    left: 'blue',
  },
  {
    id: 'scrapShield',
    name: 'Scrap Shield',
    imageUrl: 'https://imgur.com/IpXaIt5.png',
    location: 'Blacksmith',
    right: 'red',
  },
  {
    id: 'lanternDagger',
    name: 'Lantern Dagger',
    imageUrl: 'https://imgur.com/lUhb4oX.png',
    location: 'Blacksmith',
    left: 'red',
  },
  {
    id: 'lanternGauntlets',
    name: 'Lantern Gauntlets',
    imageUrl: 'https://imgur.com/qHu36qC.png',
    location: 'Blacksmith',
    left: 'green',
  },
  {
    id: 'lanternGlaive',
    name: 'Lantern Glaive',
    imageUrl: 'https://imgur.com/eHWm8TD.png',
    location: 'Blacksmith',
    bottom: 'green',
  },
  {
    id: 'lanternGreaves',
    name: 'Lantern Greaves',
    imageUrl: 'https://imgur.com/D4W5TwL.png',
    location: 'Blacksmith',
    top: 'blue',
    left: 'red',
    right: 'red',
  },
  {
    id: 'lanternHelm',
    name: 'Lantern Helm',
    imageUrl: 'https://imgur.com/ahnNZAP.png',
    location: 'Blacksmith',
    bottom: 'blue',
  },
  {
    id: 'lanternMail',
    name: 'Lantern Mail',
    imageUrl: 'https://imgur.com/1LO1Fwb.png',
    location: 'Blacksmith',
    right: 'green',
  },
  {
    id: 'lanternSword',
    name: 'Lantern Sword',
    imageUrl: 'https://imgur.com/z7EdRD8.png',
    location: 'Blacksmith',
    left: 'red',
  },
  {
    id: 'lanternCuirass',
    name: 'Lantern Cuirass',
    imageUrl: 'https://imgur.com/ndzCHjD.png',
    location: 'Blacksmith',
    left: 'green',
    right: 'green',
    top: 'blue',
    bottom: 'blue',
  },
  {
    id: 'dragonSlayer',
    name: 'Dragon Slayer',
    imageUrl: 'https://imgur.com/8bWtJGc.png',
    location: 'Blacksmith',
    right: 'red',
    top: 'blue',
  },
  {
    id: 'beaconShield',
    name: 'Beacon Shield',
    imageUrl: 'https://imgur.com/pQPur7S.png',
    location: 'Blacksmith',
  },
];
