export const monsters = [
  {
    id: 'whiteLion',
    name: 'White Lion',
  },
];

export const encounters = [
  {
    id: 'WHITE_LION_FIRST_STORY',
    monsterId: 'whiteLion',
    name: 'First Story',
  },
  {
    id: 'WHITE_LION_LEVEL_1',
    monsterId: 'whiteLion',
    name: 'Level 1',
  },
  {
    id: 'WHITE_LION_LEVEL_2',
    monsterId: 'whiteLion',
    name: 'Level 2',
  },
  {
    id: 'WHITE_LION_LEVEL_3',
    monsterId: 'whiteLion',
    name: 'Level 3',
  },
];

export const monsterBasics = [
  {
    id: 'WHITE_LION_MONSTER',
    imageUrl: 'https://imgur.com/6voXSGA.png',
    name: 'White Lion Monster',
    type: 'BASIC',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_BASIC_ACTION',
    imageUrl: 'https://imgur.com/rmgHnYU.png',
    name: 'White Lion Basic Action',
    type: 'BASIC',
    monsterId: 'whiteLion',
  },
];

export const monsterAis = [
  {
    id: 'WHITE_LION_AI_ALERT',
    imageUrl: 'https://imgur.com/PDhAtjC.png',
    name: 'Alert',
    type: 'AI',
    subType: 'MOOD',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_BAT_AROUND',
    imageUrl: 'https://imgur.com/QDbad03.png',
    name: 'Alert',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_BLOODTHIRSTY',
    imageUrl: 'https://imgur.com/GzSjzAx.png',
    name: 'Bloodthirsty',
    type: 'AI',
    subType: 'MOOD',
    level: 'A',
    token: 0,
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_BLOODY_CLAW',
    imageUrl: 'https://imgur.com/jPoBWtW.png',
    name: 'Bloody Claw',
    type: 'AI',
    subType: 'NONE',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_COMBO_CLAW',
    imageUrl: 'https://imgur.com/7DHzhW0.png',
    name: 'Combo Claw',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_CUNNING',
    imageUrl: 'https://imgur.com/4GTZeks.png',
    name: 'Cunning',
    type: 'AI',
    subType: 'TRAIT',
    level: 'S',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_GOLDEN_EYES',
    imageUrl: 'https://imgur.com/jpCj3NV.png',
    name: 'Golden Eyes',
    type: 'AI',
    subType: 'TRAIT',
    level: 'L',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_GROUND_FIGHTING',
    imageUrl: 'https://imgur.com/vYcWBcO.png',
    name: 'Ground Fighting',
    type: 'AI',
    subType: 'MOOD',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_LICK_WOUNDS',
    imageUrl: 'https://imgur.com/pnHnKno.png',
    name: 'Lick Wounds',
    type: 'AI',
    subType: 'NONE',
    level: 'A',
    heal: 1,
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_MERCILESS',
    imageUrl: 'https://imgur.com/HH6M4Gp.png',
    name: 'Merciless',
    type: 'AI',
    subType: 'TRAIT',
    level: 'S',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_REVENGE',
    imageUrl: 'https://imgur.com/NvuhLRG.png',
    name: 'Revenge',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_SMART_CAT',
    imageUrl: 'https://imgur.com/nc46gHt.png',
    name: 'Smart Cat',
    type: 'AI',
    subType: 'NONE',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_VANISH',
    imageUrl: 'https://imgur.com/qirQbPV.png',
    name: 'Vanish',
    type: 'AI',
    subType: 'DURATION',
    level: 'L',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_VICIOUS_CLAW',
    imageUrl: 'https://imgur.com/SVv2nno.png',
    name: 'Vicious Claw',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_CLAW',
    imageUrl: 'https://imgur.com/zhw8GCD.png',
    name: 'Claw',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_CLAW_2',
    imageUrl: 'https://imgur.com/zhw8GCD.png',
    name: 'Claw',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_CHOMP',
    imageUrl: 'https://imgur.com/A8cdPN5.png',
    name: 'Chomp',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_SIZE_UP',
    imageUrl: 'https://imgur.com/DeJRPOT.png',
    name: 'Size Up',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_SIZE_UP_2',
    imageUrl: 'https://imgur.com/DeJRPOT.png',
    name: 'Size Up',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_POWER_SWAT',
    imageUrl: 'https://imgur.com/Ja9cqIk.png',
    name: 'Power Swat',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_GRASP',
    imageUrl: 'https://imgur.com/veQqQyw.png',
    name: 'Grasp',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_GRASP_2',
    imageUrl: 'https://imgur.com/veQqQyw.png',
    name: 'Grasp',
    type: 'AI',
    subType: 'NONE',
    level: 'B',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_MAUL',
    imageUrl: 'https://imgur.com/yT0RvDA.png',
    name: 'Maul',
    type: 'AI',
    subType: 'NONE',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_TERRIFYING_ROAR',
    imageUrl: 'https://imgur.com/r8S2NPr.png',
    name: 'Terrifying roar',
    type: 'AI',
    subType: 'NONE',
    level: 'A',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_AI_ENRAGED',
    imageUrl: 'https://imgur.com/xEsTvK3.png',
    name: 'Enraged',
    type: 'AI',
    subType: 'MOOD',
    level: 'A',
    monsterId: 'whiteLion',
  },
];

export const monsterHitLocations = [
  {
    id: 'WHITE_LION_HIT_BEASTS_BACK',
    imageUrl: 'https://imgur.com/RbI8u22.png',
    name: "Beast's Back",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_BROW',
    imageUrl: 'https://imgur.com/46nfOfU.png',
    name: "Beast's Brow",
    type: 'hit',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_CHEST',
    imageUrl: 'https://imgur.com/8zEY8bX.png',
    name: "Beast's Chest",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_EAR',
    imageUrl: 'https://imgur.com/I7q8zYO.png',
    name: "Beast's Ear",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_ELBOW',
    imageUrl: 'https://imgur.com/XGgO5ou.png',
    name: "Beast's Elbow",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_FEMUR',
    imageUrl: 'https://imgur.com/mrFUiZb.png',
    name: "Beast's Femur",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_FLANK',
    imageUrl: 'https://imgur.com/mIYz0Uu.png',
    name: "Beast's Flank",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_HEEL',
    imageUrl: 'https://imgur.com/X3iKGNj.png',
    name: "Beast's Heel",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_KNEE',
    imageUrl: 'https://imgur.com/FiMAc8T.png',
    name: "Beast's Knee",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_MAW',
    imageUrl: 'https://imgur.com/sRYM8gH.png',
    name: "Beast's Maw",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_PAW',
    imageUrl: 'https://imgur.com/iZd2lS4.png',
    name: "Beast's Paw",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_RIBS',
    imageUrl: 'https://imgur.com/U1dDe6m.png',
    name: "Beast's Ribs",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_SCAPULAR_DELTOID',
    imageUrl: 'https://imgur.com/XEfQNzE.png',
    name: "Beast's Scapular Deltoid",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_TAIL',
    imageUrl: 'https://imgur.com/6Wzgg1I.png',
    name: "Beast's Tail",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_TEMPLE',
    imageUrl: 'https://imgur.com/YBmk1eQ.png',
    name: "Beast's Temple",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_BEASTS_TRICEP',
    imageUrl: 'https://imgur.com/lO7l34P.png',
    name: "Beast's Tricep",
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_CLEVER_PLOY',
    imageUrl: 'https://imgur.com/Bt7EyiK.png',
    name: 'Clever Ploy',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_FLESHY_GUT',
    imageUrl: 'https://imgur.com/qBIVAqi.png',
    name: 'Fleshy Gut',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_FUZZY_GROIN',
    imageUrl: 'https://imgur.com/Guf8y30.png',
    name: 'Fuzzy Groin',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_GLORIOUS_MANE',
    imageUrl: 'https://imgur.com/pt1Tn7M.png',
    name: 'Glorious Mane',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_SOFT_BELLY',
    imageUrl: 'https://imgur.com/zn1Yyzl.png',
    name: 'Soft Belly',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_STRAINING_NECK',
    imageUrl: 'https://imgur.com/v5Pz0Vd.png',
    name: 'Straining Neck',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
  {
    id: 'WHITE_LION_HIT_STRANGE_HAND',
    imageUrl: 'https://imgur.com/3zbe2YU.png',
    name: 'Strange Hand',
    type: 'HIT',
    monsterId: 'whiteLion',
  },
];
